services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=poopies

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_DSN=postgres://postgres:poopies@db:5432/exchange?sslmode=disable
      - JWT_SECRET=change-me
      - MIGRATIONS_DIR=migrations
      - PORT=8080
    ports:
      - "8080:8080"

volumes:
  db-data: